---
- name: Template nginx proxy config
  template:
    src: 'nginx_proxy.conf.j2'
    dest: '/etc/nginx/sites-available/livepeer-proxy.conf'
  notify: reload nginx

- name: Symlink nginx proxy config
  file:
    src: '/etc/nginx/sites-available/livepeer-config.conf'
    dest: '/etc/nginx/sites-enabled/livepeer-config.conf'
    state: link
  notify: reload nginx
